version: '3.7'

services:
  ctc_server:
    image: 'domcermak/ctc_server'
    container_name: 'ctc_server'
    ports:
      - '1234:1234'
    depends_on:
      - 'postgres_production'
    environment:
      PG_HOST: 'postgres_production'
      PG_PORT: '5432'
      PG_DATABASE: 'postgres'
      PG_USERNAME: 'postgres'
      PG_PASSWORD: 'postgres'
      LOG_LEVEL: 'info'
    networks:
      - ctc_network

  postgres_production:
    image: 'postgres:14.2-alpine'
    container_name: 'postgres_production'
    restart: 'always'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/sql/structure.sql:/docker-entrypoint-initdb.d/create.sql
      - ./docker/sql/data.sql:/docker-entrypoint-initdb.d/fillin.sql
    networks:
      - ctc_network

volumes:
  db-data:
    external: false

networks:
  ctc_network:
    external: false